"""initial migration

Revision ID: bfd2dbf9a586
Revises: 
Create Date: 2020-03-09 18:13:00.013883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd2dbf9a586'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_merchant', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address_street', sa.String(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_zip', sa.String(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('most_recent_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.Column('account_type', sa.Enum('checking', 'savings', name='accounttype'), nullable=True),
    sa.Column('debit_card_number', sa.String(length=16), nullable=True),
    sa.Column('credit_card_number', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('approval_needed_from', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t1employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('new_full_name', sa.String(), nullable=True),
    sa.Column('new_password_hash', sa.String(), nullable=True),
    sa.Column('new_email', sa.String(), nullable=True),
    sa.Column('new_phone', sa.String(), nullable=True),
    sa.Column('new_address_street', sa.String(), nullable=True),
    sa.Column('new_address_city', sa.String(), nullable=True),
    sa.Column('new_address_zip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('new_account_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.Enum('checking', 'savings', name='accounttype'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_from', sa.Integer(), nullable=True),
    sa.Column('account_to', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('initiation_time', sa.DateTime(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_from'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['account_to'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('new_account_requests')
    op.drop_table('info_change_requests')
    op.drop_table('t2employees')
    op.drop_table('t1employees')
    op.drop_table('requests')
    op.drop_table('administrators')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
